spring.data.mongodb.uri=mongodb://sergio:sergio1@localhost:27017/test?authSource=liverpool
server.port=8082
# Configure reactive Netty engine details
#netty.connection-timeout: 20000ms
#netty.idle-timeout: 60s
# Set base path for all reactive endpoints
#
# spring.webflux.base-path= /api
# Increase maximum in-memory buffer limit (defaults to 256KB)
#spring.webflux.codec.max-in-memory-size=10MB

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbit

